SELECT
	"id" AS DATE_DIM_ID
	,DATUM AS "DATE_ACTUAL"
	,(DATUM - to_date('1970-01-01','yyyy-mm-dd')) * 86400  AS "EPOCH"
	,TO_CHAR(DATUM, 'Day') AS DAY_NAME
	,CASE
		WHEN
			CAST(TO_CHAR(DATUM, 'D') AS NUMBER) - 1 = 0
			THEN
				7
		ELSE
			CAST(TO_CHAR(DATUM, 'D') AS NUMBER)- 1
	END AS DAY_OF_WEEK_3
	,CAST(TO_CHAR(DATUM, 'D') AS NUMBER) AS DAY_OF_WEEK_4
	,trunc(DATUM,'IW') AS FIRST_DAY_OF_WEEK_3
	,trunc(DATUM,'DAY') AS FIRST_DAY_OF_WEEK_4
	,trunc(DATUM,'MONTH') AS FIRST_DAY_OF_MONTH_1
	,trunc(DATUM,'Q') AS FIRST_DAY_OF_QUARTER_1
	,trunc(DATUM,'YEAR') AS FIRST_DAY_OF_YEAR_1
	,trunc(DATUM,'IY') AS FIRST_DAY_OF_YEAR_2
FROM
	(SELECT
		LEVEL AS "id"
		,to_date('1970-01-01','yyyy-mm-dd') + LEVEL - 1 AS DATUM
	FROM 
		DUAL
	CONNECT BY LEVEL <= 47846) list_date;
